/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MruCloseFocusPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MruCloseFocusPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.history = [];
    this.lastActiveLeaf = null;
    this.restoreInProgress = false;
    this.restoreTimer = null;
  }
  async onload() {
    const active = this.app.workspace.getMostRecentLeaf();
    if (active) {
      this.lastActiveLeaf = active;
      this.rememberLeaf(active);
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        this.onActiveLeafChange(leaf);
      })
    );
  }
  onunload() {
    if (this.restoreTimer !== null) {
      window.clearTimeout(this.restoreTimer);
      this.restoreTimer = null;
    }
  }
  onActiveLeafChange(newLeaf) {
    if (this.restoreInProgress) return;
    const previousLeaf = this.lastActiveLeaf;
    this.lastActiveLeaf = newLeaf;
    if (newLeaf) {
      this.rememberLeaf(newLeaf);
    }
    if (!previousLeaf || previousLeaf === newLeaf) return;
    if (this.restoreTimer !== null) {
      window.clearTimeout(this.restoreTimer);
    }
    this.restoreTimer = window.setTimeout(() => {
      this.restoreTimer = null;
      if (!this.leafExists(previousLeaf)) {
        const fallback = this.findFallbackLeaf(previousLeaf, newLeaf);
        if (!fallback) return;
        this.restoreInProgress = true;
        try {
          this.app.workspace.setActiveLeaf(fallback, { focus: true });
          this.lastActiveLeaf = fallback;
          this.rememberLeaf(fallback);
        } finally {
          window.setTimeout(() => {
            this.restoreInProgress = false;
          }, 0);
        }
      }
    }, 0);
  }
  rememberLeaf(leaf) {
    if (!this.isUsableLeaf(leaf)) return;
    this.history = this.history.filter((item) => item !== leaf);
    this.history.unshift(leaf);
    if (this.history.length > 50) {
      this.history.length = 50;
    }
  }
  findFallbackLeaf(closedLeaf, currentLeaf) {
    for (const leaf of this.history) {
      if (leaf === closedLeaf) continue;
      if (leaf === currentLeaf) continue;
      if (!this.leafExists(leaf)) continue;
      if (!this.isUsableLeaf(leaf)) continue;
      return leaf;
    }
    return null;
  }
  leafExists(target) {
    let exists = false;
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf === target) exists = true;
    });
    return exists;
  }
  isUsableLeaf(leaf) {
    const view = leaf.view;
    if (!view) return false;
    return view.navigation === true;
  }
};
