/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/


// main.ts
var import_obsidian = require("obsidian");
module.exports = class MruCloseFocusPlugin extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.history = [];
    this.activeLeaf = null;
    this.restoreInProgress = false;
    this.restoreTimer = null;
  }
  async onload() {
    const active = this.app.workspace.getMostRecentLeaf();
    if (active && this.isUsableLeaf(active)) {
      this.activeLeaf = active;
      this.touchHistory(active);
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        this.onActiveLeafChange(leaf);
      })
    );
  }
  onunload() {
    if (this.restoreTimer !== null) {
      window.clearTimeout(this.restoreTimer);
      this.restoreTimer = null;
    }
  }
  onActiveLeafChange(newLeaf) {
    if (this.restoreInProgress) return;
    const previousLeaf = this.activeLeaf;
    if (!previousLeaf) {
      this.activeLeaf = newLeaf;
      if (newLeaf && this.isUsableLeaf(newLeaf)) {
        this.touchHistory(newLeaf);
      }
      return;
    }
    if (newLeaf === previousLeaf) return;
    if (this.restoreTimer !== null) {
      window.clearTimeout(this.restoreTimer);
    }
    this.restoreTimer = window.setTimeout(() => {
      this.restoreTimer = null;
      const previousWasClosed = !this.leafExists(previousLeaf);
      if (previousWasClosed) {
        const fallback = this.findMostRecentSurvivingLeaf(previousLeaf);
        if (!fallback) {
          this.activeLeaf = newLeaf;
          return;
        }
        this.restoreInProgress = true;
        try {
          if (fallback !== newLeaf) {
            this.app.workspace.setActiveLeaf(fallback, { focus: true });
          }
          this.activeLeaf = fallback;
          this.touchHistory(fallback);
        } finally {
          window.setTimeout(() => {
            this.restoreInProgress = false;
          }, 0);
        }
        return;
      }
      this.activeLeaf = newLeaf;
      if (newLeaf && this.isUsableLeaf(newLeaf)) {
        this.touchHistory(newLeaf);
      }
    }, 20);
  }
  touchHistory(leaf) {
    if (!this.isUsableLeaf(leaf)) return;
    this.history = this.history.filter((item) => item !== leaf);
    this.history.unshift(leaf);
    if (this.history.length > 100) {
      this.history.length = 100;
    }
  }
  findMostRecentSurvivingLeaf(closedLeaf) {
    for (const leaf of this.history) {
      if (leaf === closedLeaf) continue;
      if (!this.leafExists(leaf)) continue;
      if (!this.isUsableLeaf(leaf)) continue;
      return leaf;
    }
    return null;
  }
  leafExists(target) {
    let exists = false;
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf === target) exists = true;
    });
    return exists;
  }
  isUsableLeaf(leaf) {
    const view = leaf.view;
    if (!view) return false;
    return view.navigation === true;
  }
};
